### ISSUE TITLE
403 When running download.sh (even after applying troubleshooting methods in readme)

### ISSUE THREAD

**Issue by that-one-arab** [facebookresearch/llama#278]
I have received my presigned URL yesterday. After applying the troubleshooting steps mentioned in both https://github.com/facebookresearch/llama/issues/41# and https://github.com/facebookresearch/llama/issues/53#issue-1606582963 I still get 403 when running the the download script.

I also get 403 when accessing the URLs that are printed in the console when running the scripts

Many people are also complaining from this error.

My presigned URL format is:
`https://<SUB_DOMAIN>.cloudfront.net/*?Policy=<STRING>&Signature=<STRING>&Key-Pair-Id=<STRING>`

**Comment by uticu** [comment]
Same here.

**Comment by cm2435** [comment]
Think this is server-side from the number of people failing to replicate #277

**Comment by nicosquare** [comment]
I can confirm I'm having the same issue after fixing all the problems mentioned in the Issues section of this repo.

**Comment by VeronicaCPerez** [comment]
Same here

**Comment by vardaan123** [comment]
same here

**Comment by sergiotasconmorales** [comment]
Same here, still can't solve the 403 issue and the link is supposed to expire in a few days :(

**Comment by PraxisWasTaken** [comment]
same here

**Comment by vtwoptwo** [comment]
same

**Comment by SummerXIATIAN** [comment]
same

**Comment by goelnaman** [comment]
I am also getting 403 error..

**Comment by anilkul98** [comment]
Same here :/

**Comment by mgagvani** [comment]
Same here. It was downloading yesterday (4/19/23) perfectly fine so it seems like a server issue most likely?

**Comment by nextsaga-rpg** [comment]
same, email is from 4/18 and for two days it's been "403 Permission denied".
Anyone sent email asking what's happening?

**Comment by mgagvani** [comment]
> same, email is from 4/18 and for two days it's been "403 Permission denied". Anyone sent email asking what's happening?

I just did, will comment here if there is a response.

**Comment by mumumu09chi** [comment]
Same here 
getting 403 error.

**Comment by boyalyn** [comment]
Same here.

**Comment by MythraV** [comment]
same here

**Comment by devthahn** [comment]
same here

**Comment by WardF** [comment]
Same here.

**Comment by sqxccdy** [comment]
Same here.

**Comment by vkp2020** [comment]
@that-one-arab did you manage to find any solution? I am facing the same on MacBook. 403.

**Comment by Tanmay06** [comment]
same here

**Comment by LucaCorvitto** [comment]
Same here, I tried all the fixes, in fact the python version of the download file is the one that works better, but it keeps saying `ERROR 403: Forbidden`. At the end of the output it prints something like this:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/87773518/233738031-e62dc75e-ded1-477d-8b31-06a431563184.png">
I think I'll write to meta too before my link expires.

**Comment by sqxccdy** [comment]
This project has been having a 403 issue for several days with no one resolving it, and it seems like there's no one maintaining it anymore. You can try searching for "pyllama" on GitHub as it should still be functional.

**Comment by oluceps** [comment]
Same here.

**Comment by mmderakhshani** [comment]
same here.

**Comment by Si13x** [comment]
Same issue here.  Got my official link on 4/18 and pulled down 7B, 13B, and 30B that evening.  Speeds were really erratic, so I decided to come back later to get 65B, hoping whatever problem the server seemed to be having would be resolved.  That was apparently a bad idea, because as of 4/19, I, too, am getting the delightful 403 FORBIDDEN error.  No configuration changes happened on my end during the relevant period, so the problem has to be server side.

Tried all the official fixes and the alternative python script that still uses your official download link.  Also tested trying to download while on VPN from numerous different USA servers in case it's region-specific.  Nada.  Pinged Meta about the issue, but given the dead silence here on their part, I'm less than optimistic.  What a mess.

@sqxccdy -- I tried the pyllama community download script in the name of science.  Guess what... 404.

**Comment by andrewmbrown** [comment]
Currently having the same issue, just a bunch of HTTP 403s. I've also sent an email to llmaccess@meta.com. Good luck everyone

**Comment by ssdavidson** [comment]
I'm having the same issue unfortunately. And my link expires tomorrow :( I sent an email, so hopefully they will at least give me an updated link.

**Comment by LucaCorvitto** [comment]
> This project has been having a 403 issue for several days with no one resolving it, and it seems like there's no one maintaining it anymore. You can try searching for "pyllama" on GitHub as it should still be functional.

I solved with this, I deleted the original llama folder and installed the pyllama one instead, inserted the link in download.sh leaving blank the target folder. I hope you guys will solve too, unfortunately Meta did not answer me yet.

**Comment by jsriram9** [comment]
ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
getting this error

**Comment by andrewmbrown** [comment]
@LucaCorvitto Are you saying that you used a URL granted permission by Meta and the download worked using pyllama? Or did you download the weights from another source?

**Comment by LucaCorvitto** [comment]
> @LucaCorvitto Are you saying that you used a URL granted permission by Meta and the download worked using pyllama? Or did you download the weights from another source?

I used the URL granted by Meta and put it in the download.sh file of the pyllama folder

**Comment by andrewmbrown** [comment]
> > @LucaCorvitto Are you saying that you used a URL granted permission by Meta and the download worked using pyllama? Or did you download the weights from another source?
> 
> I used the URL granted by Meta and put it in the download.sh file of the pyllama folder

Its the same downloading script between the LLaMA repo and PyLLaMA (with a couple line changes) so it should still not work if you are using the Meta URL.

**Comment by LucaCorvitto** [comment]
> > > @LucaCorvitto Are you saying that you used a URL granted permission by Meta and the download worked using pyllama? Or did you download the weights from another source?
> > 
> > 
> > I used the URL granted by Meta and put it in the download.sh file of the pyllama folder
> 
> Its the same downloading script between the LLaMA repo and PyLLaMA (with a couple line changes) so it should still not work if you are using the Meta URL.

I don't know why but it works, I downloaded the 7B and the 13B version, 12,5GB the first one and 25 the second one

**Comment by ukkupca** [comment]
I tried what @LucaCorvitto suggested and got the same error

**Comment by AurRod** [comment]
Hey all,
We have noticed some server errors that are related to the expiration date of the links. Effectively links expired after a day instead of a week for the emails that were sent out on the 18th of april.
We shall send some new access tokens in the upcoming days to people that received their email access on the 18th, sorry for the inconvenience!

**Comment by ivi-42** [comment]
same here, had 22h ago and now expired

**Comment by AI-PowerSolutions** [comment]
> Hey all, Thanks for bringing this out to our attention! We have noticed some server errors that are related to the expiration date of the links. Effectively links expired after a day instead of a week for the emails that were sent out on the 18th of april. We shall send some new access tokens in the upcoming days to people that received their email access on the 18th, sorry for the inconvenience!

I am having the same issue with an E-Mail send out on the 25th April! (Expired after 24 hours, Error 403)

**Comment by obiwit** [comment]
+1, email also sent out on 25th April (getting 403 error)

**Comment by gpgg** [comment]
same issue with the email sent out on 26th April.

**Comment by kcarnold** [comment]
I just received a new link, and it's working now.

**Comment by andrewmbrown** [comment]
I just got a new link too, it seems to work!

**Comment by nextsaga-rpg** [comment]
Does the new link work for you?
I got a new link 30min ago and I still get 403 error

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>---</RequestId>
<HostId>
---
</HostId>
</Error>`

**Comment by andrewmbrown** [comment]
> Does the new link work for you? I got a new link 30min ago and I still get 403 error
> 
> ```
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied</Message>
> <RequestId>---</RequestId>
> <HostId>
> ---
> </HostId>
> </Error>
> ```

Are you running it in the download.sh script?

**Comment by Tanmay06** [comment]
Just received a new link and it is working for me !!

**Comment by nextsaga-rpg** [comment]
> Are you running it in the download.sh script?

Sorry it's my bad. I cloned the repo again and forgot to modify the "Target Folder", so the permission denied is actually from my Linux system

**Comment by VeronicaCPerez** [comment]
Hi all, received the new link and it's all working now

**Comment by sishida21** [comment]
I also received a new link, and the link works correctly. Many thanks to LLAMA release team:)

**Comment by that-one-arab** [comment]
New link works! Thank you @AurRod
