### ISSUE TITLE
download.sh returns 403 forbidden error

### ISSUE THREAD

**Issue by dnwalkup** [facebookresearch/llama#373]
**What's Happening**
When attempting to download the 70B-chat model using download.sh, the model itself returns a 403 forbidden code.

**Traceback**
*Note the the policy has been removed to maintain security.
```
Downloading llama-2-70b-chat
--2023-07-18 14:56:00--  https://download.llamameta.net/llama-2-70b-chat/consolidated.00.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.110, 18.155.202.78, 18.155.202.88, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.110|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:00 ERROR 403: Forbidden.

--2023-07-18 14:56:00--  https://download.llamameta.net/llama-2-70b-chat/consolidated.01.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.78, 18.155.202.110, 18.155.202.51, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.78|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:00 ERROR 403: Forbidden.

--2023-07-18 14:56:00--  https://download.llamameta.net/llama-2-70b-chat/consolidated.02.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.51, 18.155.202.78, 18.155.202.88, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.51|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:00 ERROR 403: Forbidden.

--2023-07-18 14:56:00--  https://download.llamameta.net/llama-2-70b-chat/consolidated.03.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.110, 18.155.202.78, 18.155.202.51, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.110|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:01 ERROR 403: Forbidden.

--2023-07-18 14:56:01--  https://download.llamameta.net/llama-2-70b-chat/consolidated.04.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.51, 18.155.202.88, 18.155.202.110, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.51|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:01 ERROR 403: Forbidden.

--2023-07-18 14:56:01--  https://download.llamameta.net/llama-2-70b-chat/consolidated.05.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.88, 18.155.202.78, 18.155.202.51, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.88|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:01 ERROR 403: Forbidden.

--2023-07-18 14:56:01--  https://download.llamameta.net/llama-2-70b-chat/consolidated.06.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.88, 18.155.202.110, 18.155.202.78, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.88|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:01 ERROR 403: Forbidden.

--2023-07-18 14:56:01--  https://download.llamameta.net/llama-2-70b-chat/consolidated.07.pth?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.78, 18.155.202.51, 18.155.202.110, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.78|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:01 ERROR 403: Forbidden.

--2023-07-18 14:56:01--  https://download.llamameta.net/llama-2-70b-chat/params.json?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.110, 18.155.202.88, 18.155.202.51, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.110|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:01 ERROR 403: Forbidden.

--2023-07-18 14:56:01--  https://download.llamameta.net/llama-2-70b-chat/checklist.chk?Policy=e...
Resolving download.llamameta.net (download.llamameta.net)... 18.155.202.51, 18.155.202.88, 18.155.202.78, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.155.202.51|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 14:56:02 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found
```

**Steps to Reproduce**
`git clone https://github.com/facebookresearch/llama.git`
`cd to_llama_directory`
`source download.sh`
`enter URL`
`enter '70B-chat' as model to download`

**Comment by blevlabs** [comment]
Just tried 'source' with my download.sh script and got the same issue.

**Comment by mysterious-progression** [comment]
Same here. Their presigned urls are broken.

**Comment by rolandtannous** [comment]
yes same problem here

**Comment by alexanderfrey** [comment]
same here

**Comment by rwade42** [comment]
Same :(

**Comment by ai8hyf** [comment]
same

**Comment by wtfbbqhax** [comment]
same

**Comment by zitterbewegung** [comment]
I am also getting errors saying 403 forbidden.

**Comment by realhaik** [comment]
Yes, the download URL that is sent in the email returns 403

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>SKYPWV0JXM2WGX0E</RequestId>
<HostId>/FrUedRqzYAjkmRLenU0MYosC5qR+q27LR2WWh09+NNqSXnGXhJTP2V8Y8a1aryGUVFenNLbLBI=</HostId>
</Error>

**Comment by tensorboy** [comment]
Same issues

**Comment by efraisse** [comment]
checkout @MIBlue119's comment under issue #370

**Comment by rolandtannous** [comment]
already sent another request.. didn't get a link yet

**Comment by jxy** [comment]
Downloading `LICENSE`, `USE_POLICY.md`, `tokenizer.model`, and `tokenizer_checklist.chk` are fine, but downloading any model specific files gives 403 forbidden.

**Comment by khushpatelmd** [comment]
facing 403 forbidden error. Requested a link again and had the same issue.

**Comment by bdambrosio** [comment]
me too. sigh

**Comment by pyamin1878** [comment]
same same same

**Comment by pyamin1878** [comment]
It downloaded 5 items, and then restricted from downloading models.
![image](https://github.com/facebookresearch/llama/assets/11963396/8f5f6074-9118-4b22-ad12-947059931444)

**Comment by sivang** [comment]
Also getting this, it'd be nice if someone from Meta could chip in and provide some insight to this. thanks

**Comment by jpfyoder** [comment]
Same issue here.

**Comment by MatthewNicastro** [comment]
I did what was suggested by @efraisse and it semi worked. The non-chat models seem to fail, but the chat ones work just fine. I think this might be a server issue

**Comment by keceli** [comment]
Make sure the URL text you paste starts with: https://download.llamameta.net/. If it starts with: https://l.facebook.com/ it doesn't work.

**Comment by shi-kejian** [comment]
I fixed it by: 
1. Only manually copy (ctrl+c or cmd+c) the URL text in the email. Don't do "copy link" 
2. if 403 still occur, request a link again. I got an immediate 2nd approval. 

It seems **my 2nd approval link works 🎉, use it asap** but the first one doesn't.
![Screenshot 2023-07-18 at 3 48 54 PM](https://github.com/facebookresearch/llama/assets/32584185/85f1f3ba-165c-4578-a648-cccf9d3a26a6)

Also see issue #350  and #351

**Comment by taf2** [comment]
@shi-kejian this didn't work for me... :(

```
chmod a+x ./download.sh
./download.sh
```

I'm 90% certain they have an encoding issue in the link they send out...  so based on the hash they generate some people will get a broken link some maybe get a good link.

**Comment by faizansid77** [comment]
I am also facing the same issue

**Comment by sumeetshirgure** [comment]
Same issue

**Comment by faizansid77** [comment]
Requesting another link and downloading models one-by-one works for me

**Comment by lallousx86** [comment]
Same problem. I managed to download the non chat models, no problems. All of them. The chat models give an error.

Nothing but problems downloading today. On my second requested link and trying to get this silly thing to work.

What's funny is that Meta engineers think we are babies: "Oh, maybe you paste the wrong email link", "Oh, maybe you also copied the 'Select' word on the second line", "Oh, don't use the redirect link" ...

Meta, fix your stuff....

And thanks for your contribution.

**Comment by akashocx17** [comment]
Same stuff!! requesting again

**Comment by blevlabs** [comment]
> checkout @MIBlue119's comment under issue #370, it worked for me, he said:
> """
> @thewilltejeda / @joshvfleming Try to
> a. remove the llama directory
> b. reclone the repo
> c. resent the request to https://ai.meta.com/resources/models-and-libraries/llama-downloads/ again to get the new link
> d. cd llama
> e. chmod 755 download.sh
> f. copy the url from the newest email to the ./download.sh
> """

I got the new URL from a second request and followed the steps above from another commenter and now I can successfully download the models

**Comment by taf2** [comment]
I can report getting a new link and starting by just downloading '13b' seems to work.  Unsure if the 70b-chat will work

**Comment by blevlabs** [comment]
https://github.com/facebookresearch/llama/issues/373#issuecomment-1641199409

Scratch that - It appears only the Non-chat models work, the chat models download blank files

**Comment by blevlabs** [comment]
> I can report getting a new link and starting by just downloading '13b' seems to work.  Unsure if the 70b-chat will work
> 
> 
> 
> Interesting in my output for 13b i see one request 403'd and one is downloading... this could just be ratelimits on their servers preventing downloads?
> 
> 
> 
> https://download.llamameta.net/llama-2-13b/consolidated.00.pth -> 403'ed while
> 
> https://download.llamameta.net/llama-2-13b/consolidated.01.pth -> is downloading fine.
> 
> 
> 
> Here's the final output:
> 
> ```
> 
> 
> 
> Checking checksums
> 
> consolidated.00.pth: FAILED
> 
> consolidated.01.pth: OK
> 
> params.json: OK
> 
> md5sum: WARNING: 1 computed checksum did NOT match
> 
> ```
> 
> 
> 
> running a second time and everything fails with just:
> 
> ```
> 
> Checking checksums
> 
> md5sum: checklist.chk: no properly formatted checksum lines found
> 
> ```

I am getting the same - its getting a lot of 403s but its downloading something... Hopefully the models wont just be partially downloaded and they will be functional.

**Comment by taf2** [comment]
@blevlabs it's the same 403 issue - their servers are doing something most likely rate limts but then the files get corrupted and will forever fail.... unless you nuke the model dir... so first since this is very flaky... back things up:

```
cp -R rm  llama-2-13b/*   13b-backup/
rm -rf rm  llama-2-13b/*
./download.sh
...
13B
```

for example after many iterations:
```
2023-07-18 20:47:19 (5.65 MB/s) - ‘./llama-2-13b-chat/checklist.chk’ saved [154/154]

Checking checksums
consolidated.00.pth: OK
consolidated.01.pth: OK
params.json: OK
```

keep trying until great success.. .hopefully someone will post a torrent file to improve this process soon.

**Comment by blevlabs** [comment]
Yeah, the only one I could successfully download was Llama-2-7B, all the others are giving me the 403 forbidden issue

**Comment by MIBlue119** [comment]
@blevlabs 
You could try to download one by one with modifying the ./download.sh
I meet the same issue with you when i try to download all models. But when i set one model to download, it is worked for me.
![圖片](https://github.com/facebookresearch/llama/assets/9137836/39e0f55f-780a-4444-a576-36c9cb55177c)

**Comment by blevlabs** [comment]
@MIBlue119 Interesting, Ill have to retry. I tried to select just a few models, then just 13B, or the chat version, 7b-chat, and still ran into the 403 issues. Perhaps I need a third link, or wait a bit if there are any limits on one URL can make.

**Comment by taf2** [comment]
I can confirm if you get a 403 request a new link...

if you have output like: 
```
2023-07-18 21:08:47 (45.6 MB/s) - ‘./llama-2-70b-chat/checklist.chk’ saved [478/478]

Checking checksums
consolidated.00.pth: OK
consolidated.01.pth: OK
consolidated.02.pth: OK
consolidated.03.pth: FAILED
consolidated.04.pth: OK
consolidated.05.pth: FAILED
consolidated.06.pth: OK
consolidated.07.pth: FAILED
params.json: OK
```

Then get the new link and do this:
```
 wget 'https://download.llamameta.net/llama-2-70b-chat/consolidated.05.pth?Policy=(insert new hash)'
```

rinse and repeat. it's a FB bug

**Comment by Zombiessss** [comment]
maybe git-lfs for https://huggingface.co/meta-llama is better

**Comment by Zombiessss** [comment]
git-lfs for https://huggingface.co/meta-llama may be better

**Comment by dseddah** [comment]
Hi everyone,
I'm still having that 403 error ;( I requested a new key and still the same errors.
I've tried downloading some of them but to no luck. 

Anyone with a workaround ? I requested access via hugginface but they ask to require access for each of them...

**Comment by datanizing** [comment]
For me it was a problem of `.wgetrc`. Try to (re)move that file and try it again. Worked immediately.

**Comment by stawils** [comment]
still 403 forbidden error. requested new link.....still waiting.


Resolving download.llamameta.net (download.llamameta.net)... 3.160.212.115, 3.160.212.113, 3.160.212.74, ...
Connecting to download.llamameta.net (download.llamameta.net)|3.160.212.115|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden.
ERROR 403: Forbidden..

**Comment by mwyborski** [comment]
Thanks for wasting my time. Big brains at work.

**Comment by chrismarra** [comment]
Hi everyone, we fixed some issues with the download links yesterday - resetting your local directory and requesting a new link is the best way to start over unless you've already verified checksums and know exactly which files you need.

When you post 403s, please include the time at which you received the email so we can check whether all fixes were applied or not.

**Comment by dseddah** [comment]
> Hi everyone, we fixed some issues with the download links yesterday - resetting your local directory and requesting a new link is the best way to start over unless you've already verified checksums and know exactly which files you need.
> 
> When you post 403s, please include the time at which you received the email so we can check whether all fixes were applied or not.

Hi, here's mine:
-2023-07-19 15:08:45--  https://download.llamameta.net/llama-2-7b/checklist.chk?Policy=eyJTdGF0ZW1l(...)d9fX1dfQ__&Signature=IHTP9JLmj7yunwW1%7EsgyHZKs5RUfprt5Mn2yqeP408fl9OIM7WaRRqYzHFxMeM2Ce3x41fToFqB0uOlhJxRYw4r4AvlRtwHPmzNA-gg7aD3SQePPwe4ghWkfn4v-3jlbkRLwj5__(....)___Q__&Key-Pair-Id=K15Q_[...]_LZ
Resolving download.llamameta.net (download.llamameta.net)... 18.164.52.48, 18.164.52.8, 18.164.52.57, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.164.52.48|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden.
2023-07-19 15:08:45 ERROR 403: Forbidden..

that's the second key I've been requesting. (first on my inria account and then on gmail)

Thanks for looking into that.

Best,
Djamé

**Comment by datanizing** [comment]
Can you  the link from the email in the browser? Then I would be almost sure that it is related to `.wgetrc`

Going back to the old `.wgetrc` revived the problem for me, I also only get `ERROR 403: Forbidden..` even when `wget`tin the supplied link.

Without a `.wgetrc` the whole download ran without any problem.

**Comment by realhaik** [comment]
> Hi everyone, we fixed some issues with the download links yesterday - resetting your local directory and requesting a new link is the best way to start over unless you've already verified checksums and know exactly which files you need.
> 
> When you post 403s, please include the time at which you received the email so we can check whether all fixes were applied or not.

Was this necessary, all this funky download link generation nonsense? What have you achieved with this, except from harassing your users?
I have already went thru 3 downloads links, and now waiting for the forth one. I hope you don't block me after the 5th attempt, like you said you would. 
Thanks!

**Comment by dseddah** [comment]
> 

I don't have any ~/.wgetrc

**Comment by blevlabs** [comment]
I got a new key from facebook today, and it seems to work great. Maybe this was just an issue with yesterdays keys?

**Comment by rjalexa** [comment]
Tried all suggestions in this thread, including zapping the llama directory and re-cloning it from github AND requesting a new DL link from Meta (which thankfully arrives pretty immediately). Do not have any .wgetrc file anywhere. Still get the following errors (Central Europe Daylight time):
```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 13B
Downloading LICENSE and Acceptable Usage Policy
--2023-07-25 11:45:45--  https://download.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.67, 54.192.111.6, 54.192.111.49, ...
Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.67|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-25 11:45:45 ERROR 403: Forbidden.

--2023-07-25 11:45:45--  https://download.llamameta.net/USE_POLICY.md?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.6, 54.192.111.49, 54.192.111.29, ...
Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.6|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-25 11:45:45 ERROR 403: Forbidden.

Downloading tokenizer
--2023-07-25 11:45:45--  https://download.llamameta.net/tokenizer.model?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.49, 54.192.111.29, 54.192.111.67, ...
Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.49|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-25 11:45:45 ERROR 403: Forbidden.

--2023-07-25 11:45:45--  https://download.llamameta.net/tokenizer_checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.29, 54.192.111.67, 54.192.111.6, ...
Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.29|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-25 11:45:45 ERROR 403: Forbidden.
```

**Comment by Yuiceee** [comment]
I obtained the new URL from metaAI, and that resolved the issue.

**Comment by aswnss-m** [comment]
My problem got solved when I ran the download.sh file directly without using sh

```
sudo chmod +x ./download.sh
./download.sh
```

This fixed the problem for me

**Comment by cooltheo** [comment]
I solved it by requesting this URL twice for [https://ai.meta.com/resources/models-and-libraries/llama-downloads/](Request access to the next version of Llama). It works well now. Good luck

**Comment by rancheng** [comment]
in the email, they said
> The unique custom URL provided will remain valid for model downloads for 24 hours, and requests can be submitted multiple times.
> Now you’re ready to start building with Llama 2.

**Comment by Punny1m** [comment]
Hilariously typing "13B" with a capital "B" rather than "13b" make difference for me ...

**Comment by chinadx** [comment]
check your download url and the "download.sh" script, is it codellama or llama, they must be match.

**Comment by agunapal** [comment]
Please refer to this Download FAQ and see it helps. Happy to add more to this list based on what the community is facing
https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md

**Comment by akatutis** [comment]
Looks like that download of llama (1) models are working, but not the llama 2. if you request "Llama 2 & Llama Chat" and try using this repo to download, it will give you 403 errors. How to download llama 2 models?

**Comment by Maggodbz** [comment]
if you start the download and choose a model, make sure you are smarter than me and dont pick the names from the email but from the suggestion in the terminal

**Comment by gardeniane** [comment]
> My problem got solved when I ran the download.sh file directly without using sh
> 
> ```
> sudo chmod +x ./download.sh
> ./download.sh
> ```
> 
> This fixed the problem for me

this works for me

**Comment by njsm8** [comment]
Two changes that I have made that might have worked 
`sudo sh download.sh` instead of `sh download.sh`
entering the model as `7B,7B-chat` instead of `(7B,7B-chat)`

**Comment by jhammarstedt** [comment]
Also got this error initially but just resubmitting and getting a new link a few minutes later worked for me

**Comment by HyejinWon** [comment]
@jhammarstedt 's method is worked for me!!!

**Comment by mos-fine** [comment]
> 尝试了此线程中的所有建议，包括删除 llama 目录并从 github 重新克隆它，以及从 Meta 请求新的 DL 链接（谢天谢地，它立即到达）。任何地方都没有任何 .wgetrc 文件。仍然出现以下错误（中欧夏令时）：
> 
> ```
> Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 13B
> Downloading LICENSE and Acceptable Usage Policy
> --2023-07-25 11:45:45--  https://download.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.67, 54.192.111.6, 54.192.111.49, ...
> Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.67|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-07-25 11:45:45 ERROR 403: Forbidden.
> 
> --2023-07-25 11:45:45--  https://download.llamameta.net/USE_POLICY.md?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.6, 54.192.111.49, 54.192.111.29, ...
> Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.6|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-07-25 11:45:45 ERROR 403: Forbidden.
> 
> Downloading tokenizer
> --2023-07-25 11:45:45--  https://download.llamameta.net/tokenizer.model?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.49, 54.192.111.29, 54.192.111.67, ...
> Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.49|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-07-25 11:45:45 ERROR 403: Forbidden.
> 
> --2023-07-25 11:45:45--  https://download.llamameta.net/tokenizer_checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.29, 54.192.111.67, 54.192.111.6, ...
> Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.29|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-07-25 11:45:45 ERROR 403: Forbidden.
> ```
Have you solved this problem please, I am suffering from it

**Comment by mohbattharani** [comment]
> > 尝试了此线程中的所有建议，包括删除 llama 目录并从 github 重新克隆它，以及从 Meta 请求新的 DL 链接（谢天谢地，它立即到达）。任何地方都没有任何 .wgetrc 文件。仍然出现以下错误（中欧夏令时）：
> > ```
> > Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 13B
> > Downloading LICENSE and Acceptable Usage Policy
> > --2023-07-25 11:45:45--  https://download.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> > Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.67, 54.192.111.6, 54.192.111.49, ...
> > Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.67|:443... connected.
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2023-07-25 11:45:45 ERROR 403: Forbidden.
> > 
> > --2023-07-25 11:45:45--  https://download.llamameta.net/USE_POLICY.md?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> > Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.6, 54.192.111.49, 54.192.111.29, ...
> > Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.6|:443... connected.
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2023-07-25 11:45:45 ERROR 403: Forbidden.
> > 
> > Downloading tokenizer
> > --2023-07-25 11:45:45--  https://download.llamameta.net/tokenizer.model?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> > Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.49, 54.192.111.29, 54.192.111.67, ...
> > Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.49|:443... connected.
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2023-07-25 11:45:45 ERROR 403: Forbidden.
> > 
> > --2023-07-25 11:45:45--  https://download.llamameta.net/tokenizer_checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPzt5Pz9nZT8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjkwMzY0NjUwfX19XX0_&amp;Signature=CnrrzLPc3eKhcBfcmi%7E-CSAje%7EJL6OWHI-i5886srGbPclOddeD3ljK0Q2zGF52BlJKlc6WUIh9cxpPb8FYK-Gx0I9I2Gqe1fInzWjwmTa0fDOhKPMSjRi5Krxxm7WywIVbBkRYRlkNx8hH0Q-2SwE2srjvy3wdW-bibHofF-7Yf2-d3vXcCcF1Yyq0F2Xqe86%7Eyq8zVbroHolzkExSCengNN03nz7XLXG62Ove4WEezdOXEjcgVLH-N0oiQOfLKZWGkCo%7EhRlC3UtlLSgSzEUBEQpWTPdNdJbjSVdVk-P%7Eyi6CtUCpgyEMrV42Xp6b4L2uu%7Ehy6btPHe6J-dl1qWA__&amp;Key-Pair-Id=K15QRJLYKIFSLZ
> > Resolving download.llamameta.net (download.llamameta.net)... 54.192.111.29, 54.192.111.67, 54.192.111.6, ...
> > Connecting to download.llamameta.net (download.llamameta.net)|54.192.111.29|:443... connected.
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2023-07-25 11:45:45 ERROR 403: Forbidden.
> > ```
> 
> Have you solved this problem please, I am suffering from it

I have the same issue, I links twice but both did not work.

**Comment by mos-fine** [comment]
maybe we can try this way
![Uploading 微信图片_20231220100902.png…]()

**Comment by DanilTk** [comment]
Well, not sure if anyone still faces the problem, but when you run download.sh it will prompt you for license and then the next prompt will ask to enter the model you want to download. Here's the trick, don't use the models from email you get from meta, but use the options that pop up in terminal. E.g in email you have **Llama-2-7b-chat**, but in terminal you are given options and for chat it is **7b-chat**. This may be puzzling, but hopefully will help anyone

**Comment by R3DRUN3** [comment]
Requesting a new link solved this for me.

**Comment by bulidoge** [comment]
![835ac671ff84228787bbc0fbdc38f9c_upscayl_4x_realesrgan-x4fast](https://github.com/meta-llama/llama/assets/118815299/9bc77cee-c0d2-4f4b-a97c-205654f5804d)
THE ONLY WAY TO DO THIS IS TO RE-GET THE LINK .........

**Comment by CodeSlasher2** [comment]
Had the same issue 

instead of 7b-chat typed 7B-chat and it worked

**Comment by Xuanming13** [comment]
Faced the same issue before. 

Some say that it is related with link. So I applied for a new link and copied new link directly on the website instead of in the e-mail. It worked.

**Comment by xtameem** [comment]
same problem

**Comment by azaidelson** [comment]
Same problem. Pathetic.

**Comment by cywuuuu** [comment]
I tried to directly download it from huggingface and it works for me, hope it be helpful!

**Comment by zehrakorkusuz** [comment]
**Issue Encountered:**  
I had the same error when attempting to download all the models. Instead of manually typing all the model names, simply pressing Enter solved my problem.

**Previous Error Message:**  
```
Resolving download6.llamameta.net (download6.llamameta.net)... 18.66.218.109, 18.66.218.101, 18.66.218.114, ...
Connecting to download6.llamameta.net (download6.llamameta.net)|18.66.218.109|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-05-03 21:12:23 ERROR 403: Forbidden.
```

> getting this to _all_ model downloads...
> 
> Also getting this, it'd be nice if someone from Meta could chip in and provide some insight to this. thanks

**Comment by MaLub** [comment]
(I have the same problem, but I solve it)

You have to make sure that the associated repo is cloned.
There are corresponding repos for llama-2, llama-3, code-llama and llama guard

- codellama: https://github.com/meta-llama/codellama
- llama-3: https://github.com/meta-llama/llama3
- llama-2: https://github.com/meta-llama/llama
- llama-guard: https://github.com/meta-llama/PurpleLlama/tree/main/Llama-Guard2

All of them has a `download.sh` - copy the correct download link from the email(s). There are separate ones for every language model.

**Comment by Hzzone** [comment]
Finally I found the cause by adding `-d` to wget:
```
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might Skipping 474 bytes of body: [be too much traffic or a configuration error. Try again later, or contact the app or website owner.
```

So sad:( One needs to set a proxy to the right country.

**Comment by Josephood7** [comment]
So, instead of download multiple models at the same time like (8B,70B), **try downloading them one by one**.
When it asks to enter the list of models to download, I simply type 70B.
This works for me. 
No 403 forbidden code appears.

**Comment by pkalbhor** [comment]
You might be entering wrong model name. Choice is between 
```8B,8B-instruct,70B,70B-instruct```

**Comment by Josephood7** [comment]
@pkalbhor 
That's the case for Llama3
For Llama2, the choice is between `7b,7b-chat,13b,13b-chat,70b,70b-chat`

**Comment by gilitz** [comment]
> Hilariously typing "13B" with a capital "B" rather than "13b" make difference for me ...

worked for me too. thanks

**Comment by avinashmyerolkar** [comment]
I also got the same error saying that 403 error

but I found that the URL on email which we are pasting to download model is incorrect, Rather check with the URL coming just after filling the form on meta site itself 
There they will provide 2 URL 
1. Meta Llama 3: 
2.Meta Llama Guard 2:

with email the url comes is  2.Meta Llama Guard 2: , which dont allow to download model, and hence everyone facing the issue

check with 1. Meta Llama 3:  URL from the same page instead from email , It may work for u also
![Screenshot 2024-06-09 182926](https://github.com/meta-llama/llama/assets/134629810/10640ebb-795d-47b5-8351-7214bb9e6e46)

**Comment by NingZhenPeng** [comment]
ERROR 403: Forbidden solution appears when downloading llama3

==========================question=================================

Downloading LICENSE and Acceptable Usage Policy
--2024-06-12 11:12:40--  https://download5.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiODBqZW4zcWZxd3E5MXlhcWtyOTUxN2F5IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQ1LmxsYW1hbWV0YS
Resolving download5.llamameta.net (download5.llamameta.net)... 18.155.192.52, 18.155.192.4, 18.155.192.93, ...
Connecting to download5.llamameta.net (download5.llamameta.net)|18.155.192.52|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-06-12 11:12:41 ERROR 403: Forbidden.

=======================Possible solutions======================================

To set HTTP proxy in Git Bash, you should use the following format：
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890


Verify proxy settings
After the setup is complete, you can check whether the environment variables are set correctly by running the following command：
echo $http_proxy
echo $https_proxy

==============Screenshot successfully downloaded================

<img width="956" alt="Download llama error" src="https://github.com/meta-llama/llama/assets/19367709/5bff1542-9800-48ec-83a0-bbf09ae9d137">

**Comment by JustinKai0527** [comment]
I also got this problem, I fix by only install one model
in terminal
1) enter your url
2) and just text the model you want 7B
notice that can't text eg. [[7B]] I don't know why this will forbidden
just text 7B you can get the model.ckpt

**Comment by Retto** [comment]
The signed URL expiration duration is 24 hours. it gives a 403 error if expires. 
Another reason for the 403 error is related to the wrong model name for the signed URL. 

We're grabbing the signed URL from the website. if you select the latest model It is the 3.1 model. Also, you should select the right models to execute the corresponding download.sh file.  Because of the download.sh file is different for each model version. Available model names are also different for each model version. 

Please git clone https://github.com/meta-llama/llama-models project and visit your desired model. Run the download.sh file under the right folder. 

![image](https://github.com/user-attachments/assets/d8e6587e-3fed-406b-b098-840c31dbb03f)

**Comment by clousea26** [comment]
If you're running into this issue for downloading LLaMa 3.1, make sure you're cloning the right Git repo. Meta's docs for [Running LLaMa on Linux](https://llama.meta.com/docs/llama-everywhere/running-meta-llama-on-linux/) are still referencing llama3's repo rather than llama3.1's. Silly mistake on my part.
Thanks to [Piotr-rogal's answer in another thread](https://github.com/meta-llama/llama/issues/760#issuecomment-2268308391) that helped me with this realization.

**Comment by eunkich** [comment]
Had this issue with download.sh. The same link worked when I used llama-stack instead.
```sh
pip install llama-stack
llama model download --source meta --model-id {MODEL_ID}
```

**Comment by anelocyber** [comment]
this is how i fixed the issue -->>

first run this  "pip install llama-stack" without quotes
then run this :
"llama model list"
Run "llama download --source meta --model-id Llama3.2-3B-Instruct"
N.B choose your model id in my case its Llama3.2-3B-Instruct

**Comment by Renchunzi-Xie** [comment]
I fix this problem by match the correct URL with --model_id in "llama download --source meta --model-id XXX"

**Comment by zhirshfeld** [comment]
Was not able to solve the problem and only work around it by running the following:
pip install llama-stack
llama model list --show-all
llama model download --source meta --model-id  MODEL_ID (I used Llama3.1-70B , which I got approval from Meta site for)

When prompted, I provided the URL form the email I received from 'AI At Meta'

I still don't understand why the download.sh didn't work and Meta doesn't provide any guidance or troubleshooting informations.

**Comment by dylan-green** [comment]
> I fixed this problem by matching the correct URL with --model_id in "llama download --source meta --model-id XXX".
> 
> ![Screenshot 2024-12-30 191839](https://github.com/user-attachments/assets/3e041a9a-9fba-43f5-8741-cfd5dc78cbb8)

KING - this is the problem.

You request access to a particular model version, then the URL you receive in the email is locked to that version. Model ID's need to match what you requested and try to download. THANK YOU.

**Comment by tranmanhdat** [comment]
what's problems with Llama3-8B, I cannot download that models, however it works with Llama3.1-8B instead!

**Comment by jackassplus** [comment]
Having a similar? issue. 3 of the 4 downloads succeeds, only the token fails:
llama model download --source meta --model-id Llama-2-13b
![Image](https://github.com/user-attachments/assets/b1308a21-0d82-4de1-abf4-a832b17f4eaf)

**Comment by kirapika2** [comment]
> Having a similar? issue. 3 of the 4 downloads succeeds, only the token fails: llama model download --source meta --model-id Llama-2-13b ![Image](https://github.com/user-attachments/assets/b1308a21-0d82-4de1-abf4-a832b17f4eaf)

I had the same situation but I was able to resolve it.
I was able to easily get the llama-2 model by running `download.sh` from this repository!

By another way, You can run `llama model download --source meta --model-id Llama-2-7b` by no error.
It seems that torkenizer.model exists only at smallest model.
If Llama-2-13b is specified, the `llama model download` will fail, and if Llama-2-7b is specified, it will succeed.
I hope it works out.

**Comment by jackassplus** [comment]
so the bug is definitely in llama-cli, rather than download.sh. I'll raise the issue in the correct place.
