### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by alescire94** [facebookresearch/llama#50]
Got the following error when executing:
`torchrun --nproc_per_node 1 example.py --ckpt_dir models/7B --tokenizer_path models/tokenizer.model`

![image](https://user-images.githubusercontent.com/13464974/222400735-2a506fa7-a6aa-49ed-9960-b1891b814420.png)

additional info:
cuda: 11.4
GPU: NVIDIA GeForce 3090
torch             1.12.1
Ubuntu 20.04.2 LTS

Anyone knows how to solve it?
Thanks in advance!

**Comment by sz85512678** [comment]
Have the same issue, running on a MacBook Pro.

**Comment by christophelebrun** [comment]
Same, running on MacBook Pro M1.

**Comment by Amadeus-AI** [comment]
Try change
```
torch.distributed.init_process_group("nccl")
```
to
```
torch.distributed.init_process_group("gloo")
```

**Comment by Elvincth** [comment]
> Try change
> 
> ```
> torch.distributed.init_process_group("nccl")
> ```
> 
> to
> 
> ```
> torch.distributed.init_process_group("gloo")
> ```

Running on a MacBook pro m1, after changing to this got a new error: `AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`

**Comment by AmirFone** [comment]
> Running on a MacBook pro m1, after changing to this got a new error: `AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`

I'm getting the same error have you been able to resolve it?

**Comment by b0kch01** [comment]
> > Running on a MacBook pro m1, after changing to this got a new error: `AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`
> 
> I'm getting the same error have you been able to resolve it?

To run on m1, You have to go through the repository and modify every line that references CUDA to use the CPU instead. Even then, the sample prompt took over an hour to run for me on the smallest llama model.

**Comment by jaygdesai** [comment]
> > > Running on a MacBook pro m1, after changing to this got a new error: `AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`
> > 
> > 
> > I'm getting the same error have you been able to resolve it?
> 
> To run on m1, You have to go through the repository and modify every line that references CUDA to use the CPU instead. Even then, the sample prompt took over an hour to run for me on the smallest llama model.

I am trying to do the same. Can you tell exactly how did you achieve the same?

**Comment by b0kch01** [comment]
Make the following changes if you want to use CPU

`example.py`
```python
# torch.distributed.init_process_group("nccl")  you don't have/didn't properly setup gpus 
torch.distributed.init_process_group("gloo") # uses CPU 
# torch.cuda.set_device(local_rank) remove for the same reasons


# torch.set_default_tensor_type(torch.cuda.HalfTensor)
torch.set_default_tensor_type(torch.FloatTensor) # I think you can also use torch.HalfTensor
```

`generation.py`
```python
# tokens = torch.full((bsz, total_len), self.tokenizer.pad_id).cuda().long()
tokens = torch.full((bsz, total_len), self.tokenizer.pad_id).long()
```

`model.py`
```python
self.cache_k = torch.zeros(
    (args.max_batch_size, args.max_seq_len, self.n_local_heads, self.head_dim)
)#.cuda()
self.cache_v = torch.zeros(
    (args.max_batch_size, args.max_seq_len, self.n_local_heads, self.head_dim)
)#.cuda()
```

**Comment by AmirFone** [comment]
Thank you! @b0kch01

**Comment by jaygdesai** [comment]
I am now stuck with following issue after following instructions provided by @b0kch01: 

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/3757893/222562250-efa97a2d-dc41-403e-8d0b-6cdf197c3494.png">

Any guidance?

**Comment by paulutsch** [comment]
<img width="1355" alt="Bildschirmfoto 2023-03-02 um 23 26 47" src="https://user-images.githubusercontent.com/76492498/222573979-6ba47eac-49ac-4473-a08c-64e7ee1fb3b6.png">

After following @b0kch01's advices, I'm stuck here. Can anyone help out?

**Comment by b0kch01** [comment]
> After following @b0kch01's advices, I'm stuck here. Can anyone help out?

When the log says `MP=0`, it means it cannot find any of the weights in the path you provided

**Comment by Urammar** [comment]
Those errors both typically indicate you havent actually pointed at either the model or the tokenizer. I noticed the tokenizer doesnt seem to get downloaded with the 7B

I'll upload it here to save you the trouble, this should be extracted to whatever directory you set your download to (1 above your 7B model directory itself) or just manually point to it with that command line

[tokenizer.zip](https://github.com/facebookresearch/llama/files/10879229/tokenizer.zip)

**Comment by paulutsch** [comment]
> Those errors both typically indicate you havent actually pointed at either the model or the tokenizer. I noticed the tokenizer doesnt seem to get downloaded with the 7B
> 
> I'll upload it here to save you the trouble, this should be extracted to whatever directory you set your download to (1 above your 7B model directory itself) or just manually point to it with that command line
> 
> [tokenizer.zip](https://github.com/facebookresearch/llama/files/10879229/tokenizer.zip)

Okay, I got it working now. For some reason, the download.sh did not work as expected – it did not download the weights. Luckily, I found this edit online in a conversation in the llama GitHub repo: https://github.com/facebookresearch/llama/pull/39/files

I implemented the changes and now the weights are downloading.

**Comment by mawilson1234** [comment]
I'm getting stuck in a different way after following @b0kch01's changes. I'm not running into the MP=0 issue, but I get some warnings about being unable to initialize the client and server sockets. Otherwise it looks similar to @jaygdesai's issue but with exitcode 7 instead of 9.
 
![error](https://user-images.githubusercontent.com/5022150/222789944-3ac5cd51-8818-4897-91d7-f93ceb6d54b2.png)

**Comment by b0kch01** [comment]
If you'd like, you can try my [llama cpu fork](https://github.com/b0kch01/llama-cpu.git). Tested to work on my Macbook Pro M1 Max

**Comment by turbo** [comment]
Just in case someone's going to ask for MPS (M1/2 GPU support): the code uses `view_as_complex`, which is neither supported, nor does it have any PYTORCH_ENABLE_MPS_FALLBACK due to memory sharing issues. Even modifying the code to use MPS does not enable GPU support on Apple Silicon until https://github.com/pytorch/pytorch/issues/77764 is fixed. So only CPU for now, but `@b0kch01`'s version works nicely 🙂

**Comment by hopto-dot** [comment]
I'm trying to run llama on my gpu with the following command after changing "nccl" to "gloo" to fix the already established error:
`torchrun --nproc_per_node auto example.py --ckpt_dir "consolidated.00.pth" --tokenizer_path "tokenizer.model"`

And I get the following:
```
C:\Users\Username\Documents\Git\llama>torchrun --nproc_per_node auto example.py --ckpt_dir "consolidated.00.pth" --tokenizer_path "tokenizer.model"
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [3ca52znvmj.adobe.io]:29500 (system error: 10049 - The requested address is not valid in its context.).
> initializing model parallel with size 4
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "C:\Users\Username\Documents\Git\llama\example.py", line 120, in <module>
    fire.Fire(main)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Username\Documents\Git\llama\example.py", line 75, in main
    local_rank, world_size = setup_model_parallel()
  File "C:\Users\Username\Documents\Git\llama\example.py", line 26, in setup_model_parallel
    Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
torch.cuda.set_device(local_rank)  File "C:\Users\Username\Documents\Git\llama\example.py", line 120, in <module>
  File "C:\Users\Username\Documents\Git\llama\example.py", line 120, in <module>
  File "C:\Users\Username\Documents\Git\llama\example.py", line 120, in <module>

              File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 326, in set_device
fire.Fire(main)fire.Fire(main)fire.Fire(main)


torch._C._cuda_setDevice(device)  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire

            AttributeErrorcomponent_trace = _Fire(component, args, parsed_flag_args, context, name)component_trace = _Fire(component, args, parsed_flag_args, context, name)component_trace = _Fire(component, args, parsed_flag_args, context, name):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire

module 'torch._C' has no attribute '_cuda_setDevice'
      File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire

component, remaining_args = _CallAndUpdateTrace(
component, remaining_args = _CallAndUpdateTrace(component, remaining_args = _CallAndUpdateTrace(  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace


      File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
component = fn(*varargs, **kwargs)      File "C:\Users\Username\Documents\Git\llama\example.py", line 75, in main

  File "C:\Users\Username\Documents\Git\llama\example.py", line 75, in main
    local_rank, world_size = setup_model_parallel()component = fn(*varargs, **kwargs)

local_rank, world_size = setup_model_parallel()  File "C:\Users\Username\Documents\Git\llama\example.py", line 26, in setup_model_parallel
  File "C:\Users\Username\Documents\Git\llama\example.py", line 75, in main

          File "C:\Users\Username\Documents\Git\llama\example.py", line 26, in setup_model_parallel
torch.cuda.set_device(local_rank)local_rank, world_size = setup_model_parallel()
  File "C:\Users\Username\Documents\Git\llama\example.py", line 26, in setup_model_parallel

torch.cuda.set_device(local_rank)      File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 326, in set_device

torch.cuda.set_device(local_rank)      File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 326, in set_device

torch._C._cuda_setDevice(device)      File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 326, in set_device

torch._C._cuda_setDevice(device)    AttributeError
torch._C._cuda_setDevice(device): AttributeError
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice': module 'torch._C' has no attribute '_cuda_setDevice'module 'torch._C' has no attribute '_cuda_setDevice'


ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16076) of binary: C:\Users\Username\AppData\Local\Programs\Python\Python310\python.exe
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\run.py", line 762, in main
    run(args)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\run.py", line 753, in run
    elastic_launch(
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\launcher\api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\distributed\launcher\api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-03-03_21:58:36
  host      : DESKTOP-SLIQCDH.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 6384)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-03-03_21:58:36
  host      : DESKTOP-SLIQCDH.lan
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2116)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-03-03_21:58:36
  host      : DESKTOP-SLIQCDH.lan
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 8196)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-03_21:58:36
  host      : DESKTOP-SLIQCDH.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 16076)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by mawilson1234** [comment]
Unfortunately, I'm still unable to run anything using @b0kch01's `llama-cpu` repo on Linux.
```
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
Locating checkpoints
Found MP=1 checkpoints
Creating checkpoint instance...
Grabbing params...
Loading model arguments...
Creating tokenizer...
Creating transformer...
-- Creating embedding
-- Creating transformer blocks (32)

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 13822) of binary: /gpfs/gibbs/project/frank/maw244/conda_envs/llama/bin/python3.10
Traceback (most recent call last):
	File "/gpfs/gibbs/project/frank/maw244/conda_envs/llama/bin/torchrun", line 8, in <module>
		sys.exit(main())
	File "/gpfs/gibbs/project/frank/maw244/conda_envs/llama/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
		return f(*args, **kwargs)
	File "/gpfs/gibbs/project/frank/maw244/conda_envs/llama/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
		run(args)
	File "/gpfs/gibbs/project/frank/maw244/conda_envs/llama/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
		elastic_launch(
	File "/gpfs/gibbs/project/frank/maw244/conda_envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
		return launch_agent(self._config, self._entrypoint, list(args))
	File "/gpfs/gibbs/project/frank/maw244/conda_envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
		raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
======================================================
example.py FAILED
------------------------------------------------------
Failures:
<NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
time      : 2023-03-03_17:31:31
host      : c14n02.grace.hpc.yale.internal
rank      : 0 (local_rank: 0)
exitcode  : -9 (pid: 13822)
error_file: <N/A>
traceback : Signal 9 (SIGKILL) received by PID 13822
======================================================
```

Here's the version on the cluster:
```
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.9 (Maipo)
Release:        7.9
Codename:       Maipo
```

**Comment by jiyaos** [comment]
Hi, II'm stuck here, following @b0kch01's llama-cpu repo on my mac. Any suggestion? 
<img width="1328" alt="Screenshot 2023-03-04 at 2 17 11 AM" src="https://user-images.githubusercontent.com/100000512/222894322-d0d3fc1a-0311-4085-b142-5a4c780b0766.png">

**Comment by paulutsch** [comment]
> <img alt="Screenshot 2023-03-04 at 2 17 11 AM" width="1328" src="https://user-images.githubusercontent.com/100000512/222894322-d0d3fc1a-0311-4085-b142-5a4c780b0766.png">
> 
> Hi, I'm stuck here, following @b0kch01's llama-cpu repo on my mac. Any suggestion? Thanks.

I‘m facing the same issue, but only with the 7B model. It seems like the consolidated.01.pth file doesn’t get downloaded when running the download.sh file: the consolidated.01.pth file is the only one I get a 403 status instead of 200.

I opened a new issue [here](https://github.com/facebookresearch/llama/issues/96#issuecomment-1454365480).

**Comment by CupsGum** [comment]
@turbo I wish you had made that comment a few hours earlier! I spent a while trying to get this to run on the GPU on Apple Silicon.

I noticed that `precompute_freqs_cis()` in `model.py` uses the Complex64 dtype.
When trying to run on the GPU, I get the following error:
> `libc++abi: terminating with uncaught exception of type c10::TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype.`

Does that also require PyTorch to add support for complex dtypes on top of adding support for `view_as_complex()`? Or is that a limitation in MPS or the hardware itself?

**Comment by jiyaos** [comment]
Thank you @Urammar

**Comment by astelmach01** [comment]
> > > Running on a MacBook pro m1, after changing to this got a new error: `AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`
> > 
> > 
> > I'm getting the same error have you been able to resolve it?
> 
> To run on m1, You have to go through the repository and modify every line that references CUDA to use the CPU instead. Even then, the sample prompt took over an hour to run for me on the smallest llama model.

Doesn't pytorch [support the apple silicon GPU](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/)

**Comment by piex-1** [comment]
When I was using my own jetson agx orin developer kit, I also had this error. I checked online and found that jetson does not seem to support NCCL. Is this normal, because I don’t want to use the CPU to run。
![Screenshot from 2023-07-26 21-30-02](https://github.com/facebookresearch/llama/assets/91685063/74cff663-fd96-4e40-9c57-9d40cc91e851)

**Comment by alex5956** [comment]
> Try change
> 
> ```
> torch.distributed.init_process_group("nccl")
> ```
> 
> to
> 
> ```
> torch.distributed.init_process_group("gloo")
> ```

where ?

**Comment by albertodepaola** [comment]
Closing as author is inactive. If anyone has further questions, feel free to open a new issue. For future reference, check both [llama](https://github.com/facebookresearch/llama) and [llama-recipes](https://github.com/facebookresearch/llama-recipes) repos for getting started guides.

**Comment by hua3721** [comment]
This solution works for me: https://github.com/meta-llama/llama/pull/947
